version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=devsecops-thinkcloudly_thinkcloudly -Dsonar.organization=DevSecOps-Thinkcloudly -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1ed48170431874d55c022e22716af3909ec2149e
